name: first workflow

on:
  push:
    branches: ["main","develop"]
jobs:
  example-job:
    runs-on: ubuntu-latest
    steps: 
      - name: print welcome msg
        run: echo "welcome to githab actions and CI/CD "
      
        
    
      
